#!/usr/bin/env node
/**
 * Build the host probe: five fixture decks and a Script Lab snippet that
 * inserts them and asks the six questions in `docs/DESIGN.md` section 13.
 *
 *   npm run build:lib
 *   npm run probe
 *
 * The decks are built HERE, by the engine, and embedded in the snippet as
 * base64, so the snippet needs no libraries, does no zip work in a hostile
 * runtime, and can be pasted into Script Lab with nothing else installed.
 * Every zip timestamp is pinned (`stableZip`), so the output is byte-stable on
 * any machine and CI diffs the committed `probe/probe-snippet.ts` against a
 * fresh build.
 *
 * The decks:
 *   LISTED    two slides, both listed — the package as PowerPoint writes it
 *   PRUNED    the same, with slide 2's <p:sldId> AND relationship removed, part kept
 *   UNLISTED  the same, with only slide 2's <p:sldId> removed
 *   SINGLE    one slide, for the insert-then-delete order question
 *   UNDO      one slide carrying a package tag, left behind for the Ctrl+Z question
 *
 * Every judgement about what comes back lives in `src/host/probe.ts`, which is
 * tested; the snippet only collects. `scripts/read-answers.mjs` reads a sheet.
 */
import { writeFileSync } from "node:fs";
import { Pkg, PKG_REL_NS, P_NS, element, elements } from "../dist-lib/core/index.js";
import { API_FLOOR } from "../dist-lib/host/capability.js";
import { API_SETS, PROBE_MARKER, PROBE_TAG, PROBE_UNDO_VALUE } from "../dist-lib/host/probe.js";
import { makeDeck, stableZip } from "./probe-fixture.mjs";

const b64 = (bytes) => Buffer.from(bytes).toString("base64");

const listedBytes = await makeDeck([
  { text: "SSF Slide Elements probe P1", creationId: 424201 },
  { text: "SSF Slide Elements probe P2", creationId: 424202 },
]);

/** The two-slide deck with slide 2 taken out of the slide list, and out of the relationships when asked. */
async function prune(dropRelationship) {
  const pkg = await Pkg.open(listedBytes);
  const pres = await pkg.doc("ppt/presentation.xml");
  const list = element(pres, P_NS, "sldIdLst");
  const second = elements(list, P_NS, "sldId")[1];
  const rId = second.getAttribute("r:id");
  second.parentNode.removeChild(second);
  if (dropRelationship) {
    const rels = await pkg.doc("ppt/_rels/presentation.xml.rels");
    for (const rel of elements(rels, PKG_REL_NS, "Relationship")) {
      if (rel.getAttribute("Id") === rId) rel.parentNode.removeChild(rel);
    }
  }
  // The engine re-files the parts it edited with the clock; pin them like the rest.
  return b64(stableZip(await pkg.toBytes()));
}

const LISTED = b64(listedBytes);
const PRUNED = await prune(true);
const UNLISTED = await prune(false);
const SINGLE = b64(await makeDeck([{ text: "SSF Slide Elements probe S", creationId: 424203 }]));
const UNDO = b64(
  await makeDeck([
    {
      text: "SSF Slide Elements probe — press Ctrl+Z, then run the snippet again",
      creationId: 424204,
      tags: [[PROBE_TAG, PROBE_UNDO_VALUE]],
    },
  ]),
);

const snippet = `/*
 * SSF Slide Elements — host probe
 *
 * Paste this whole file into a blank Script Lab snippet in PowerPoint and press
 * Run. It appends slides to the end of the current deck, asks its questions,
 * removes what it added, and prints a JSON block. docs/PROBE.md has the steps.
 *
 * It leaves ONE slide at the end of the deck on purpose, for the Ctrl+Z
 * question: press Ctrl+Z once on the slide canvas and run it again. The second
 * run removes that slide whether or not Ctrl+Z did.
 *
 * COPY THE JSON BACK. It is the answer sheet, and nothing in the add-in should
 * be built on a guess about any of these.
 *
 * Generated by scripts/build-probe.mjs — do not edit here.
 */

const LISTED_DECK = "${LISTED}";
const PRUNED_DECK = "${PRUNED}";
const UNLISTED_DECK = "${UNLISTED}";
const SINGLE_DECK = "${SINGLE}";
const UNDO_DECK = "${UNDO}";
const PROBE_TAG = "${PROBE_TAG}";
const PROBE_MARKER = "${PROBE_MARKER}";
const API_FLOOR = "${API_FLOOR}";
const API_SETS = ${JSON.stringify(API_SETS)};

type Formatting = "KeepSourceFormatting" | "UseDestinationTheme";

interface PartsSummary {
  total: number;
  slides: number;
  masters: number;
  layouts: number;
  themes: number;
  comments: number;
  authors: boolean;
  media: number;
}

/** The same summary as src/host/probe.ts; test/probe.test.ts holds the two to the same answers. */
function summarizeParts(names: string[]): PartsSummary {
  const count = (re: RegExp): number => names.filter((n) => re.test(n)).length;
  return {
    total: names.length,
    slides: count(/^ppt\\/slides\\/slide\\d+\\.xml$/),
    masters: count(/^ppt\\/slideMasters\\/slideMaster\\d+\\.xml$/),
    layouts: count(/^ppt\\/slideLayouts\\/slideLayout\\d+\\.xml$/),
    themes: count(/^ppt\\/theme\\/theme\\d+\\.xml$/),
    comments: count(/^ppt\\/(comments|modernComments)\\//),
    authors: names.indexOf("ppt/authors.xml") >= 0,
    media: count(/^ppt\\/media\\//),
  };
}

/** Every call is bounded. On this host a stall is death, not slowness. */
function withTimeout<T>(p: Promise<T>, ms: number, what: string): Promise<T> {
  return Promise.race([
    p,
    new Promise<T>((_, reject) => setTimeout(() => reject(new Error(\`gave up waiting for: \${what}\`)), ms)),
  ]);
}

const message = (e: unknown): string => (e instanceof Error ? e.message : String(e));

function supports(version: string): boolean {
  try {
    return Office.context.requirements.isSetSupported("PowerPointApi", version);
  } catch {
    return false;
  }
}

async function slideCount(): Promise<number> {
  return PowerPoint.run(async (context) => {
    const count = context.presentation.slides.getCount();
    await context.sync();
    return count.value;
  });
}

/** How many masters the deck has, or undefined on a host below 1.3. */
async function masterCount(): Promise<number | undefined> {
  if (!supports("1.3")) return undefined;
  try {
    return await withTimeout(
      PowerPoint.run(async (context) => {
        const count = context.presentation.slideMasters.getCount();
        await context.sync();
        return count.value;
      }),
      15000,
      "counting the masters",
    );
  } catch {
    return undefined;
  }
}

/** The ids of the slides at positions from..to-1, read through getItemAt in batches of forty. */
async function positionalIds(from: number, to: number): Promise<string[]> {
  const out: string[] = [];
  for (let start = from; start < to; start += 40) {
    const end = Math.min(to, start + 40);
    const ids = await withTimeout(
      PowerPoint.run(async (context) => {
        const handles = [];
        for (let i = start; i < end; i++) {
          const slide = context.presentation.slides.getItemAt(i);
          slide.load("id");
          handles.push(slide);
        }
        await context.sync();
        return handles.map((h) => h.id);
      }),
      20000,
      \`reading slide ids \${start} to \${end}\`,
    );
    out.push(...ids);
  }
  return out;
}

/**
 * The bytes of the presentation this is running in, and how long they took.
 *
 * The control arm for question one, and the timing for question six:
 * \`getFileAsync\` is the floor's read and the file route reads the whole deck
 * for every insert.
 */
function currentDeck(): Promise<{ base64: string; ms: number; bytes: number }> {
  const started = Date.now();
  return new Promise((resolve, reject) => {
    Office.context.document.getFileAsync(Office.FileType.Compressed, { sliceSize: 4194304 }, (res) => {
      if (res.status !== Office.AsyncResultStatus.Succeeded) {
        reject(new Error(res.error ? res.error.message : "getFileAsync would not open the file"));
        return;
      }
      const file = res.value;
      const chunks: string[] = [];
      let bytes = 0;
      const next = (i: number): void => {
        if (i >= file.sliceCount) {
          file.closeAsync();
          resolve({ base64: btoa(chunks.join("")), ms: Date.now() - started, bytes });
          return;
        }
        file.getSliceAsync(i, (sl) => {
          if (sl.status !== Office.AsyncResultStatus.Succeeded) {
            file.closeAsync();
            reject(new Error(sl.error ? sl.error.message : "getSliceAsync refused a slice"));
            return;
          }
          const data = sl.value.data as number[];
          bytes += data.length;
          // Chunked, because apply() on a whole slice blows the argument limit.
          let s = "";
          for (let j = 0; j < data.length; j += 0x8000) {
            s += String.fromCharCode.apply(null, data.slice(j, j + 0x8000));
          }
          chunks.push(s);
          next(i + 1);
        });
      };
      next(0);
    });
  });
}

interface InsertResult {
  before: number;
  after: number;
  ms: number;
  error?: string;
  mastersBefore?: number;
  mastersAfter?: number;
}

/**
 * Insert a package after a target slide, and measure what happened.
 *
 * Without a target the host inserts at the FRONT; the default target is the
 * last slide, read by position. A caller may pass an id it read itself.
 */
async function insertDeck(base64: string, formatting: Formatting, targetId?: string): Promise<InsertResult> {
  const before = await slideCount();
  const mastersBefore = await masterCount();
  const started = Date.now();
  let error: string | undefined;
  try {
    await withTimeout(
      PowerPoint.run(async (context) => {
        let id = targetId;
        if (id === undefined) {
          const last = context.presentation.slides.getItemAt(before - 1);
          last.load("id");
          await context.sync();
          id = last.id;
        }
        context.presentation.insertSlidesFromBase64(base64, { formatting, targetSlideId: id });
        await context.sync();
      }),
      // Sixty seconds was short once on a sibling's third sheet, on an insert
      // that had landed both its slides. The own-deck arm inserts a copy of
      // every slide, so a large deck needs the room.
      120000,
      "inserting a deck",
    );
  } catch (e) {
    error = message(e);
  }
  const after = await slideCount();
  const mastersAfter = await masterCount();
  return { before, after, ms: Date.now() - started, error, mastersBefore, mastersAfter };
}

/** Positional, never by id: a slide this run added does not resolve by id here. */
async function sweep(deckAtStart: number, added: number): Promise<string> {
  const deckNow = await slideCount();
  const grew = deckNow - deckAtStart;
  const count = Math.min(added, grew);
  const from = deckNow - count;
  if (count <= 0 || from < deckAtStart) return \`left everything alone (start \${deckAtStart}, now \${deckNow})\`;
  try {
    await withTimeout(
      PowerPoint.run(async (context) => {
        // Highest index first, so removing one cannot shift another.
        for (let i = from + count - 1; i >= from; i--) context.presentation.slides.getItemAt(i).delete();
        await context.sync();
      }),
      60000,
      "removing the probe's slides",
    );
    return \`removed \${count} slide(s) from index \${from}\`;
  } catch (e) {
    return \`could not clean up: \${message(e)}\`;
  }
}

/**
 * The part names in a package, read from its zip central directory.
 *
 * Names only — never content. The central directory rather than a scan for
 * local headers: the four-byte signature occurs inside compressed data often
 * enough that a scan invents parts. Works on the binary string \`atob\` returns
 * rather than a Uint8Array: a deck is tens of megabytes and the copy buys
 * nothing here.
 */
interface ZipEntry {
  name: string;
  method: number;
  compressed: number;
  offset: number;
}

function entriesOf(s: string): ZipEntry[] {
  const u16 = (i: number): number => s.charCodeAt(i) | (s.charCodeAt(i + 1) << 8);
  const u32 = (i: number): number => u16(i) + u16(i + 2) * 0x10000;
  // The EOCD is last, after a comment of at most 65535 bytes.
  let eocd = -1;
  for (let i = s.length - 22; i >= 0 && i >= s.length - 22 - 65535; i--) {
    if (s.charCodeAt(i) === 0x50 && s.charCodeAt(i + 1) === 0x4b && s.charCodeAt(i + 2) === 0x05 && s.charCodeAt(i + 3) === 0x06) {
      eocd = i;
      break;
    }
  }
  if (eocd < 0) throw new Error("no end-of-central-directory record — this is not a zip");
  const count = u16(eocd + 10);
  let at = u32(eocd + 16);
  const entries: ZipEntry[] = [];
  for (let n = 0; n < count; n++) {
    if (s.charCodeAt(at) !== 0x50 || s.charCodeAt(at + 1) !== 0x4b || s.charCodeAt(at + 2) !== 0x01 || s.charCodeAt(at + 3) !== 0x02) {
      throw new Error("central directory entry " + n + " is not where the header said");
    }
    const nameLen = u16(at + 28);
    entries.push({ name: s.substr(at + 46, nameLen), method: u16(at + 10), compressed: u32(at + 20), offset: u32(at + 42) });
    at += 46 + nameLen + u16(at + 30) + u16(at + 32);
  }
  return entries;
}

function partNamesOf(binary: string): string[] {
  return entriesOf(binary).map((e) => e.name);
}

/** One part's text, inflated in the browser. Undefined when the runtime cannot inflate or the part is absent. */
async function partTextOf(binary: string, name: string): Promise<string | undefined> {
  const entry = entriesOf(binary).find((e) => e.name === name);
  if (!entry) return undefined;
  const u16 = (i: number): number => binary.charCodeAt(i) | (binary.charCodeAt(i + 1) << 8);
  const dataAt = entry.offset + 30 + u16(entry.offset + 26) + u16(entry.offset + 28);
  const raw = new Uint8Array(entry.compressed);
  for (let i = 0; i < entry.compressed; i++) raw[i] = binary.charCodeAt(dataAt + i);
  if (entry.method === 0) return new TextDecoder().decode(raw);
  if (entry.method !== 8 || typeof DecompressionStream === "undefined") return undefined;
  const stream = new Blob([raw]).stream().pipeThrough(new DecompressionStream("deflate-raw"));
  return new Response(stream).text();
}

/** The <p:sldId id="…"> values in the file's own order. */
async function sldIdListOf(binary: string): Promise<string[] | undefined> {
  const xml = await partTextOf(binary, "ppt/presentation.xml");
  if (xml === undefined) return undefined;
  const list = /<p:sldIdLst>([\\s\\S]*?)<\\/p:sldIdLst>/.exec(xml);
  if (!list) return [];
  const ids: string[] = [];
  const re = /<p:sldId\\s[^>]*\\bid="(\\d+)"/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(list[1])) !== null) ids.push(m[1]);
  return ids;
}

/**
 * Question 2: insert after a slide, then delete that slide by position.
 *
 * P1 stands in for the slide the user is on, S for the rebuilt copy the
 * engine inserts after it, P2 for the slide behind. The engine's "onto this
 * slide" is exactly: insert S after P1, prove the deck grew, delete P1 by
 * index, and expect [S, P2] where [P1, P2] was.
 *
 * S is first aimed at P1 BY ID, which is a slide this run just added — the
 * case a second "as a new slide" insert meets, and one the web is documented
 * to refuse for getItem(id). If that is refused, S is aimed at the user's own
 * last slide instead, so the order half is still asked.
 */
async function orderProbe(deckAtStart: number): Promise<Record<string, unknown>> {
  const out: Record<string, unknown> = {};
  try {
    const n = await slideCount();
    out.n = n;
    out.first = await insertDeck(LISTED_DECK, "KeepSourceFormatting");
    if ((await slideCount()) !== n + 2) {
      out.error = "the two-slide insert did not land exactly two slides, so the order question was not asked";
      out.sweep = await sweep(n, (await slideCount()) - n);
      return out;
    }
    const [p1, p2] = await positionalIds(n, n + 2);
    out.afterFirst = [p1, p2];

    let second = await insertDeck(SINGLE_DECK, "KeepSourceFormatting", p1);
    let landed = second.after - second.before;
    out.targetAdded = { ok: second.error === undefined && landed === 1, error: second.error };
    let p1Index = n;
    if (!(out.targetAdded as { ok: boolean }).ok) {
      // Take back anything that half-landed, then aim at the user's last slide.
      out.sweepAfterRefusal = await sweep(n + 2, (await slideCount()) - (n + 2));
      const [userLast] = await positionalIds(n - 1, n);
      second = await insertDeck(SINGLE_DECK, "KeepSourceFormatting", userLast);
      landed = second.after - second.before;
      p1Index = n + 1;
    }
    out.second = second;
    if (landed !== 1) {
      out.error = "the single-slide insert did not land exactly one slide, so the delete half was not asked";
      out.sweep = await sweep(n, (await slideCount()) - n);
      return out;
    }
    out.afterSecond = await positionalIds(n, n + 3);
    out.deletedIndex = p1Index;
    await withTimeout(
      PowerPoint.run(async (context) => {
        context.presentation.slides.getItemAt(p1Index).delete();
        await context.sync();
      }),
      30000,
      "deleting P1 by position",
    );
    out.afterDelete = await positionalIds(n, n + 2);
  } catch (e) {
    out.error = message(e);
  }
  out.sweep = await sweep(deckAtStart, (await slideCount()) - deckAtStart);
  return out;
}

/**
 * Question 3: what getSelectedSlides answers, and where those slides are.
 *
 * Read-only about the selection: it reports what was selected and never sets
 * anything. The positional read is capped at 120 slides, in batches, so a
 * large deck does not turn this into a hundred syncs.
 */
async function selectionProbe(ownBinary: string | undefined): Promise<Record<string, unknown>> {
  const out: Record<string, unknown> = {};
  if (!supports("1.5")) {
    out.supported = false;
    return out;
  }
  out.supported = true;
  try {
    out.selectedIds = await withTimeout(
      PowerPoint.run(async (context) => {
        const selected = context.presentation.getSelectedSlides();
        selected.load("items/id");
        await context.sync();
        return selected.items.map((s) => s.id);
      }),
      15000,
      "reading the selected slides",
    );
    const deckSize = await slideCount();
    out.deckSize = deckSize;
    const upTo = Math.min(deckSize, 120);
    const positional = await positionalIds(0, upTo);
    out.positionalRead = positional.length;
    out.selectedIndexes = (out.selectedIds as string[]).map((id) => positional.indexOf(id));
    // The API's id is "<sldId id>#<something>"; the first half is the file's
    // <p:sldId id>, so the two orders can be compared without the rels.
    if (ownBinary !== undefined) {
      const fileIds = await sldIdListOf(ownBinary);
      if (fileIds !== undefined) {
        out.sldIdLstEntries = fileIds.length;
        const prefixes = positional.map((id) => id.split("#")[0]);
        out.apiIdsHaveHash = positional.every((id) => id.indexOf("#") > 0);
        out.sldIdLstMatches = prefixes.every((p, i) => p === fileIds[i]);
        out.sldIdLstHead = fileIds.slice(0, 12);
        out.apiIdsHead = positional.slice(0, 12);
      }
    }
  } catch (e) {
    out.error = message(e);
  }
  return out;
}

/**
 * Question 4: does exportAsBase64Presentation drop parts the file route keeps?
 *
 * Both arms cover every slide in the deck, or the export would legitimately
 * lack the parts belonging to slides it was not asked for. Timed, for question
 * six: the export is the other candidate read.
 */
async function exportProbe(ownNames: string[] | undefined): Promise<Record<string, unknown>> {
  const out: Record<string, unknown> = {};
  if (!supports("1.10")) {
    out.supported = false;
    return out;
  }
  out.supported = true;
  if (ownNames === undefined) {
    out.error = "the deck's own bytes were not read, so there is nothing to compare the export against";
    return out;
  }
  try {
    const started = Date.now();
    const exportedBase64 = await withTimeout(
      PowerPoint.run(async (context) => {
        const slides = context.presentation.slides;
        slides.load("items/id");
        await context.sync();
        const bytes = slides.exportAsBase64Presentation(slides.items.map((s) => s.id));
        await context.sync();
        return bytes.value;
      }),
      120000,
      "exporting every slide in the deck",
    );
    out.ms = Date.now() - started;
    const binary = atob(exportedBase64);
    out.bytes = binary.length;
    const exported = partNamesOf(binary);
    const inExport = new Set(exported);
    const inSource = new Set(ownNames);
    out.source = summarizeParts(ownNames);
    out.exported = summarizeParts(exported);
    // Capped: a deck with two hundred dropped media parts must not push the
    // one part this question is about off the end of the list.
    out.missing = ownNames.filter((n) => !inExport.has(n)).slice(0, 40);
    out.addedByExport = exported.filter((n) => !inSource.has(n)).slice(0, 40);
  } catch (e) {
    out.error = message(e);
  }
  return out;
}

/**
 * Question 5, first half: is the slide a previous run left behind still here?
 *
 * Looks at the last five slides for the probe's tag. Tags are 1.3; below
 * that the answer is "unsupported" and the reader falls back to counts.
 */
async function findUndoSlide(): Promise<{ found: boolean | "unsupported"; index?: number; error?: string }> {
  if (!supports("1.3")) return { found: "unsupported" };
  try {
    const count = await slideCount();
    const from = Math.max(0, count - 5);
    return await withTimeout(
      PowerPoint.run(async (context) => {
        const tags = [];
        for (let i = from; i < count; i++) {
          const tag = context.presentation.slides.getItemAt(i).tags.getItemOrNullObject(PROBE_TAG);
          tag.load("value,isNullObject");
          tags.push({ i, tag });
        }
        await context.sync();
        const hit = tags.find((t) => !t.tag.isNullObject);
        return hit ? { found: true, index: hit.i } : { found: false };
      }),
      20000,
      "looking for the slide a previous run left behind",
    );
  } catch (e) {
    return { found: false, error: message(e) };
  }
}

interface Marker {
  takenAt: string;
  deckBeforeLeave: number;
}

/**
 * Question 5, the marker: what tells a second run from a first once Ctrl+Z
 * has taken the slide.
 *
 * The document's settings live outside the undo stack, so a note written
 * BEFORE the slide is left survives the Ctrl+Z that removes the slide. Before
 * it, never after: a settings save is reported to disable undo on Excel
 * (office-js#3141), and a save after the insert would take the user's one
 * Ctrl+Z away from the very insert this question is about. PowerPoint on the
 * web measured otherwise on 2026-09-10 (a save after an add still left Ctrl+Z
 * on the add); the order costs nothing and holds on hosts not yet measured.
 */
function readMarker(): { found: boolean; value?: Marker; error?: string } {
  try {
    const value = Office.context.document.settings.get(PROBE_MARKER);
    return value ? { found: true, value: value as Marker } : { found: false };
  } catch (e) {
    return { found: false, error: message(e) };
  }
}

function saveSettings(what: string): Promise<string> {
  return withTimeout(
    new Promise<string>((resolve) => {
      Office.context.document.settings.saveAsync((res) =>
        resolve(
          res.status === Office.AsyncResultStatus.Succeeded
            ? "saved"
            : \`failed: \${res.error ? res.error.message : "no error text"}\`,
        ),
      );
    }),
    20000,
    what,
  );
}

async function writeMarker(value: Marker): Promise<{ written: boolean; status: string }> {
  try {
    Office.context.document.settings.set(PROBE_MARKER, value);
    const status = await saveSettings("saving the marker");
    return { written: status === "saved", status };
  } catch (e) {
    return { written: false, status: message(e) };
  }
}

async function clearMarker(): Promise<string> {
  try {
    Office.context.document.settings.remove(PROBE_MARKER);
    return await saveSettings("clearing the marker");
  } catch (e) {
    return message(e);
  }
}

async function main() {
  const started = Date.now();
  const answers: Record<string, unknown> = {
    probe: "ssf-slide-elements",
    takenAt: new Date().toISOString(),
    platform: Office.context.platform,
    host: Office.context.diagnostics?.version ?? "unknown",
    requirementSets: API_SETS.filter(supports),
    floor: API_FLOOR,
  };

  // Question 5, second run: the slide the first run left behind. Found, it is
  // removed by position before anything else, so the deck this run measures
  // is the user's own.
  const undoAtStart = await findUndoSlide();
  if (undoAtStart.found === true && undoAtStart.index !== undefined) {
    const before = await slideCount();
    await PowerPoint.run(async (context) => {
      context.presentation.slides.getItemAt(undoAtStart.index as number).delete();
      await context.sync();
    });
    (undoAtStart as Record<string, unknown>).removed = \`removed the tagged slide at index \${undoAtStart.index} (\${before} → \${await slideCount()})\`;
  }
  answers.undoAtStart = undoAtStart;

  // The marker the previous run wrote before it left that slide. It survives
  // the Ctrl+Z the slide does not, so a second run knows what it is even
  // with the slide gone — and never leaves a slide of its own. Cleared here,
  // so the run after this one is a first run again.
  const marker = readMarker();
  const secondRun = undoAtStart.found === true || marker.found;
  answers.undoMarker = marker.found ? { found: true, value: marker.value, cleared: await clearMarker() } : marker;

  const deckAtStart = await slideCount();
  answers.deckAtStart = deckAtStart;

  // The deck's own bytes: the control for question one, the timing for
  // question six, and the part list every later comparison is against.
  let ownBase64: string | undefined;
  let ownBinary: string | undefined;
  let ownNames: string[] | undefined;
  try {
    const own = await withTimeout(currentDeck(), 120000, "reading this presentation's own bytes");
    ownBase64 = own.base64;
    ownBinary = atob(own.base64);
    ownNames = partNamesOf(ownBinary);
    answers.ownRead = { ms: own.ms, bytes: own.bytes };
    answers.partsAtStart = summarizeParts(ownNames);
  } catch (e) {
    answers.ownRead = { error: message(e) };
  }

  // Question 1, control arms: the deck inserts itself, under both formatting
  // modes, swept between them so each starts from the user's own deck. The
  // master count before and after says whether an insert brings a copy of a
  // master the deck already has.
  if (ownBase64 !== undefined) {
    answers.insertOwn = await insertDeck(ownBase64, "KeepSourceFormatting");
    answers.sweepOwn = await sweep(deckAtStart, (await slideCount()) - deckAtStart);
    answers.insertOwnDestTheme = await insertDeck(ownBase64, "UseDestinationTheme");
    answers.sweepOwnDestTheme = await sweep(deckAtStart, (await slideCount()) - deckAtStart);
  } else {
    answers.insertOwn = { skipped: "the deck's own bytes could not be read" };
    answers.insertOwnDestTheme = { skipped: "the deck's own bytes could not be read" };
  }

  // Question 1, the pruning arms.
  answers.insertListed = await insertDeck(LISTED_DECK, "KeepSourceFormatting");
  answers.insertPruned = await insertDeck(PRUNED_DECK, "KeepSourceFormatting");
  answers.insertUnlisted = await insertDeck(UNLISTED_DECK, "KeepSourceFormatting");
  answers.sweepPruning = await sweep(deckAtStart, (await slideCount()) - deckAtStart);

  // Question 2, and whether a just-added slide can be a target.
  answers.order = await orderProbe(deckAtStart);

  // Question 3, read-only.
  answers.selection = await selectionProbe(ownBinary);

  // Question 4, timed for question 6.
  answers.exportParts = await exportProbe(ownNames);

  // Everything the arms above added and did not take back.
  answers.sweep = await sweep(deckAtStart, (await slideCount()) - deckAtStart);

  // Question 5, first run: leave one tagged slide behind for Ctrl+Z. Never
  // twice in a row — a second run has found the first one's slide or its
  // marker. The marker goes in BEFORE the slide, so the user's one Ctrl+Z
  // lands on the insert and nothing this run does after it can move it.
  const leaveBehind = !secondRun;
  if (leaveBehind) {
    const deckBeforeLeave = await slideCount();
    const marked = await writeMarker({ takenAt: answers.takenAt as string, deckBeforeLeave });
    answers.undo = {
      leftBehind: true,
      deckBeforeLeave,
      marker: marked,
      insert: await insertDeck(UNDO_DECK, "KeepSourceFormatting"),
    };
  } else {
    answers.undo = { leftBehind: false, previous: marker.value };
  }

  // The package at the end, so the reader can say what the sweep could not
  // reach: a master, a theme, a layout that came in with an insert.
  try {
    const own = await withTimeout(currentDeck(), 120000, "reading this presentation's own bytes again");
    answers.ownReadAtEnd = { ms: own.ms, bytes: own.bytes };
    answers.partsAtEnd = summarizeParts(partNamesOf(atob(own.base64)));
  } catch (e) {
    answers.ownReadAtEnd = { error: message(e) };
  }
  answers.deckAtEnd = await slideCount();
  answers.totalMs = Date.now() - started;

  console.log("=== SSF SLIDE ELEMENTS ANSWER SHEET — copy everything between the markers ===");
  console.log(JSON.stringify(answers, null, 2));
  console.log("=== END ===");
  if (leaveBehind) {
    console.log(
      "One slide was left at the END of the deck on purpose. Click the slide canvas, press Ctrl+Z once, then Run this snippet again and copy the second sheet too.",
    );
  } else if (undoAtStart.found === true) {
    console.log(
      "The slide the previous run left behind was still there and was removed. The deck should be as you found it.",
    );
  } else {
    console.log(
      "The slide the previous run left behind was already gone; its marker was still here and has been cleared. The deck should be as you found it.",
    );
  }
}

main().catch((e) => console.error("the probe itself failed:", e));
`;

writeFileSync("probe/probe-snippet.ts", snippet);
console.log(
  `probe/probe-snippet.ts written (${snippet.length} bytes; decks ${[LISTED, PRUNED, UNLISTED, SINGLE, UNDO].map((d) => d.length).join(" + ")} base64 chars)`,
);
